url:
  baseUrl: /chatApp
spring:
  kafka:
    topic: ChatTopic
    producer:
      bootstrap-servers: localhost:9092
      keySerializer: 'org.apache.kafka.common.serialization.StringSerializer'
      valueSerializerr: 'org.apache.kafka.common.serialization.JsonSerializer'
appMessage:
  messageContext:
    addNewUser: "added new user "
    removeUser: "remove user "

