url:
  baseUrl: /chatApp
spring:
  kafka:
    topic: ChatTopic
    bootstrap-servers: localhost:9092
    producer:
      keySerializer: 'org.apache.kafka.common.serialization.StringSerializer'
      valueSerializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
    consumer:
      groupId: group_id
      keyDeserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
      valueDeserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
appMessage:
  messageContext:
    addNewUser: "add new user "
    removeUser: "remove user "

MASK_ID_NAME: true

configuration:
  admin:
    user: ADMIN


